#ifndef CONFIG_H
#define CONFIG_H

#define SCREEN_WIDTH 800
#define SCREEN_HEIGHT 600

#define PLAYER_START_POSITION_X (SCREEN_WIDTH/2)
#define PLAYER_START_POSITION_Y (SCREEN_HEIGHT*0.875f)
#define PLAYER_START_POSITION ((Vector2){PLAYER_START_POSITION_X, PLAYER_START_POSITION_Y})
#define PLAYER_START_HEALTHS (3)


#endif